DATA SEGMENT
SCORES DB 56H, 4DH, 5DH, 52H, 64H, 47H, 51H, 5BH, 4FH, 61H
MAX_SCORE DB 0
MAX_SCORE_INDEX DB 0
MIN_SCORE DB 0
MIN_SCORE_INDEX DB 0
DATA ENDS

CODE SEGMENT
ASSUME CS:CODE, DS:DATA
START:
MOV AX, DATA
MOV DS, AX
MOV DI, 3000H
MOV CX, 10
LEA SI, SCORES      
COPY_SCORE:
MOV AL, [SI]
MOV [DI], AL
INC SI
INC DI
LOOP COPY_SCORE
LEA SI, SCORES
MOV BX, 0  
MOV CX, 0FFFFH 
MOV DX, 0 
FIND_SCORES:
MOV AL, [SI]
CMP AL, BL
JA UPDATE_MAX
CMP AL, CL
JB UPDATE_MIN
INC SI
INC DX
CMP DX, 10
JB FIND_SCORES
JMP STORE_RESULTS

UPDATE_MAX:
MOV BL, AL
MOV MAX_SCORE, AL
MOV MAX_SCORE_INDEX, DL
INC SI
INC DX
CMP DX, 10
JB FIND_SCORES
JMP STORE_RESULTS

UPDATE_MIN:
MOV CL, AL
MOV MIN_SCORE, AL
MOV MIN_SCORE_INDEX, DL
INC SI
INC DX
CMP DX, 10
JB FIND_SCORES
JMP STORE_RESULTS

STORE_RESULTS:
MOV AL, MAX_SCORE_INDEX
MOV [3100H], AL
MOV AL, MAX_SCORE
MOV [3101H], AL
MOV AL, MIN_SCORE_INDEX
MOV [3200H], AL
MOV AL, MIN_SCORE
MOV [3201H], AL
MOV AX, 4C00H
INT 21H

CODE ENDS
END START