DATA SEGMENT
    NUM DB 8BH
DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE, DS:DATA
START:
    MOV AX, DATA
    MOV DS, AX
    MOV AL, NUM  
    AND AL, 81H  
    CMP AL, 81H 
    JE SET_100H  
    MOV BYTE PTR [100H], 0 
    JMP END_PROGRAM
SET_100H:
    MOV BYTE PTR [100H], 1 
END_PROGRAM:
    MOV AX, 4C00H
    INT 21H
CODE ENDS
END START