DATA SEGMENT
    NUM1 DB 05CH
    NUM2 DB 0A1H 
    NUM3 DB 86H
DATA ENDS

CODE SEGMENT
    ASSUME CS:CODE, DS:DATA
START:
    MOV AX, DATA
    MOV DS, AX
    MOV AL, NUM1  
    CMP AL, NUM2  
    JAE SKIP1 
    MOV AL, NUM2  
SKIP1:
    CMP AL, NUM3  
    JAE SKIP2    
    MOV AL,NUM3  
SKIP2:
    MOV [3000H], AL 
    MOV AX, 4C00H
    INT 21H
CODE ENDS
END START